blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/:vendor_name/:package_name/discussions/new?category=q-a
    about: Ask for help
  - name: Request a feature
    url: https://github.com/:vendor_name/:package_name/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://grebban.slack.com/archives/C19H0E5A9
    about: Notify team for sensitive bugs
  - name: Report a bug
    url: https://github.com/:vendor_name/:package_name/issues/new
    about: Report a reproducable bug
